### ISSUE TITLE
Missing netflix movies

### ISSUE THREAD

**Issue by ancientgoth** [Matchoo95/JP-Subtitles#8]
I notice that (all?) Japanese Netflix movies are missing. I have ripped the subtitles as srt files, could these be added to the repo?

**Comment by Matchoo95** [comment]
If you still have them then sure.

**Comment by FredericoGauz** [comment]
That would be great!

**Comment by ancientgoth** [comment]
I do, but have no permission to upload

**Comment by Matchoo95** [comment]
Are you able to send a pull request? If not, if you have them uploaded else where then post a link and I'll add them myself.

**Comment by ancientgoth** [comment]
Will do, though this will take the repo above 2gb which seems to be the Github free repo limit

**Comment by ancientgoth** [comment]
Actually, taking a look at Itazuraneko, it seems a lot of the stuff I have is already on there so might just close this issue
